# Site settings
title: Ph03N1x
description: A CTF writeups page.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ph03N1x
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Cyber Security Enthusiast
email: ph03n1xflys@gmail.com
twitter_username: lorem_ipsum
github_username:  AbijithPrasanthan
gplus_username:   Abijith Prasanthan

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
